version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/giantswarm/gsctl
    steps:
      - checkout
      - run:
          name: Install kubectl
          command: |
            kubectl_version="$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)"
            curl -s -LO https://storage.googleapis.com/kubernetes-release/release/${kubectl_version}/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      # tests
      - run:
          name: go test
          command: |
            go test -v ./...
      - run:
          name: go build
          command: |
            go build -v
      - run:
          name: Execute the built binary
          command: ./gsctl info
      - run:
          name: Post coverage to Codecov.io
          command: |
            bash ./test_coverage.sh
            bash <(curl -s https://codecov.io/bash)
